#!/usr/bin/env bash
# Rofi-based display manager for Hyprland (Lua config, 0.55+).
# Deps: rofi, jq, hyprctl (jq: sudo pacman -S jq)
#
# NOTE: `hyprctl keyword` does not work under the Lua config parser --
# it silently no-ops. All live changes go through `hyprctl eval` calling
# the same hl.monitor() function the config file itself uses.

set -euo pipefail

MONITORS_LUA="$HOME/.config/hypr/monitors.lua"
STATE_DIR="$HOME/.config/hypr/.display-menu-state"
mkdir -p "$STATE_DIR"

rofi_menu() {
    rofi -dmenu -i -p "$1"
}

refresh_json() {
    hyprctl monitors -j
}

# Applies a monitor config live via hyprctl eval.
# $1 = the Lua table body, e.g. '{ output = "eDP-1", mode = "1920x1080@60.00", position = "0x0", scale = 1.25 }'
apply_monitor() {
    hyprctl eval "hl.monitor($1)"
}

# Rewrites monitors.lua from scratch based on CURRENT live state of every
# connected monitor. Simple + robust: no partial-file editing, no risk of
# stale/duplicate blocks. Re-run after every change.
save_all_monitors() {
    local json
    json=$(refresh_json)
    {
        echo "-- Auto-generated by display-menu.sh"
        echo "-- Reflects live monitor state at last change. Don't hand-edit -- it will be overwritten."
        echo ""
        echo "$json" | jq -r '.[] |
            "hl.monitor({\n" +
            "    output    = \"\(.name)\",\n" +
            "    mode      = \"\(.width)x\(.height)@\(.refreshRate)\",\n" +
            "    position  = \"\(.x)x\(.y)\",\n" +
            "    scale     = \(.scale),\n" +
            "    transform = \(.transform),\n" +
            "})\n"'
    } > "$MONITORS_LUA"
}

# Computes what mon's new x,y should be to sit directly touching target's
# edge, given mon's (possibly not-yet-applied) width/height/scale. Doesn't
# apply anything -- just prints "Xx Y". Positions are logical (post-scale)
# pixels, which is what Hyprland's position field expects.
compute_relative_position() {
    local mon_w="$1" mon_h="$2" mon_scale="$3" target="$4" dir="$5"
    local json; json=$(refresh_json)

    local t_x t_y t_w t_h t_scale
    t_x=$(echo "$json" | jq -r --arg m "$target" '.[] | select(.name==$m) | .x')
    t_y=$(echo "$json" | jq -r --arg m "$target" '.[] | select(.name==$m) | .y')
    t_w=$(echo "$json" | jq -r --arg m "$target" '.[] | select(.name==$m) | .width')
    t_h=$(echo "$json" | jq -r --arg m "$target" '.[] | select(.name==$m) | .height')
    t_scale=$(echo "$json" | jq -r --arg m "$target" '.[] | select(.name==$m) | .scale')

    local t_lw t_lh my_lw my_lh
    t_lw=$(awk -v w="$t_w" -v s="$t_scale" 'BEGIN{printf "%d", w/s}')
    t_lh=$(awk -v h="$t_h" -v s="$t_scale" 'BEGIN{printf "%d", h/s}')
    my_lw=$(awk -v w="$mon_w" -v s="$mon_scale" 'BEGIN{printf "%d", w/s}')
    my_lh=$(awk -v h="$mon_h" -v s="$mon_scale" 'BEGIN{printf "%d", h/s}')

    local new_x=$t_x new_y=$t_y
    case "$dir" in
        "Left of")  new_x=$((t_x - my_lw)) ;;
        "Right of") new_x=$((t_x + t_lw)) ;;
        "Above")    new_y=$((t_y - my_lh)) ;;
        "Below")    new_y=$((t_y + t_lh)) ;;
    esac

    echo "${new_x}x${new_y}"
}

# Used by the standalone "Position" menu action: computes + applies a
# monitor's position relative to another, using its CURRENT dimensions,
# and records the relationship to STATE_DIR for later resolution/scale
# changes to reuse.
position_relative() {
    local mon="$1" target="$2" dir="$3"
    local json; json=$(refresh_json)
    local my_w my_h my_scale
    my_w=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name==$m) | .width')
    my_h=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name==$m) | .height')
    my_scale=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name==$m) | .scale')

    local pos; pos=$(compute_relative_position "$my_w" "$my_h" "$my_scale" "$target" "$dir")
    apply_monitor "{ output = \"$mon\", position = \"$pos\" }"
    printf '%s\t%s\n' "$target" "$dir" > "$STATE_DIR/$mon"
}

# If this monitor was previously positioned relative to another one, get
# that relationship. First checks the state file (from a prior use of the
# Position menu); if that's missing, falls back to inferring it from
# CURRENT live geometry -- i.e. finding which other monitor's edge this
# one is currently touching. Must be called BEFORE a resolution/scale
# change, while the geometry still correctly reflects the relationship.
# Prints "target<TAB>dir" and returns 0, or returns 1 if no relation found.
get_relation() {
    local mon="$1"
    local state_file="$STATE_DIR/$mon"
    if [ -f "$state_file" ]; then
        local target dir
        IFS=$'\t' read -r target dir < "$state_file"
        if echo "$(refresh_json)" | jq -e --arg t "$target" '.[] | select(.name==$t)' > /dev/null 2>&1; then
            printf '%s\t%s\n' "$target" "$dir"
            return 0
        fi
    fi

    # Infer from live geometry: is mon's edge currently touching another
    # monitor's opposite edge (within a couple px of rounding slop)?
    local json; json=$(refresh_json)
    local mx my mw mh ms mlw mlh
    mx=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name==$m) | .x')
    my=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name==$m) | .y')
    mw=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name==$m) | .width')
    mh=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name==$m) | .height')
    ms=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name==$m) | .scale')
    mlw=$(awk -v w="$mw" -v s="$ms" 'BEGIN{printf "%d", w/s}')
    mlh=$(awk -v h="$mh" -v s="$ms" 'BEGIN{printf "%d", h/s}')

    local abs; abs() { local n=$1; echo $(( n<0 ? -n : n )); }

    local others; others=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name!=$m) | .name')
    local o
    while IFS= read -r o; do
        [ -z "$o" ] && continue
        local ox oy ow oh os olw olh
        ox=$(echo "$json" | jq -r --arg m "$o" '.[] | select(.name==$m) | .x')
        oy=$(echo "$json" | jq -r --arg m "$o" '.[] | select(.name==$m) | .y')
        ow=$(echo "$json" | jq -r --arg m "$o" '.[] | select(.name==$m) | .width')
        oh=$(echo "$json" | jq -r --arg m "$o" '.[] | select(.name==$m) | .height')
        os=$(echo "$json" | jq -r --arg m "$o" '.[] | select(.name==$m) | .scale')
        olw=$(awk -v w="$ow" -v s="$os" 'BEGIN{printf "%d", w/s}')
        olh=$(awk -v h="$oh" -v s="$os" 'BEGIN{printf "%d", h/s}')

        if [ "$(abs $(( (my + mlh) - oy )) )" -le 2 ]; then
            printf '%s\t%s\n' "$o" "Above"; return 0
        elif [ "$(abs $(( my - (oy + olh) )) )" -le 2 ]; then
            printf '%s\t%s\n' "$o" "Below"; return 0
        elif [ "$(abs $(( (mx + mlw) - ox )) )" -le 2 ]; then
            printf '%s\t%s\n' "$o" "Left of"; return 0
        elif [ "$(abs $(( mx - (ox + olw) )) )" -le 2 ]; then
            printf '%s\t%s\n' "$o" "Right of"; return 0
        fi
    done <<< "$others"

    return 1
}

json=$(refresh_json)

# --- Step 1: pick a monitor ---
choice=$(echo "$json" | jq -r '.[] |
    "\(.name)  |  \(.width)x\(.height)@\(.refreshRate|floor)Hz  |  pos \(.x),\(.y)  |  scale \(.scale)"' \
    | rofi_menu "Select display")
[ -z "$choice" ] && exit 0
mon=$(echo "$choice" | awk '{print $1}')

# --- Step 2: pick an action ---
action=$(printf "Position\nResolution\nScale\nRotation\nEnable\nDisable\nMirror another display\nReset to auto\n" \
    | rofi_menu "$mon")
[ -z "$action" ] && exit 0

case "$action" in
    "Position")
        others=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name!=$m) | .name')
        if [ -z "$others" ]; then
            echo "Only one display connected." | rofi_menu "Position"
            exit 0
        fi
        target=$(echo "$others" | rofi_menu "Position relative to")
        [ -z "$target" ] && exit 0
        dir=$(printf "Left of\nRight of\nAbove\nBelow\n" | rofi_menu "Direction")
        [ -z "$dir" ] && exit 0

        position_relative "$mon" "$target" "$dir"
        ;;

    "Resolution")
        mode=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name==$m) | .availableModes[]' \
            | rofi_menu "Resolution")
        [ -z "$mode" ] && exit 0
        # availableModes look like "1920x1080@60.00Hz" -- hyprctl wants no "Hz"
        mode=${mode%Hz}
        new_w=$(echo "$mode" | sed -E 's/^([0-9]+)x([0-9]+)@.*/\1/')
        new_h=$(echo "$mode" | sed -E 's/^([0-9]+)x([0-9]+)@.*/\2/')

        relation=$(get_relation "$mon" || true)
        if [ -n "$relation" ]; then
            rel_target=$(echo "$relation" | cut -f1)
            rel_dir=$(echo "$relation" | cut -f2)
            my_scale=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name==$m) | .scale')
            pos=$(compute_relative_position "$new_w" "$new_h" "$my_scale" "$rel_target" "$rel_dir")
            # Single call: resolution + repositioned-for-that-resolution
            # together, so Hyprland never sees an intermediate overlap.
            apply_monitor "{ output = \"$mon\", mode = \"$mode\", position = \"$pos\" }"
            printf '%s\t%s\n' "$rel_target" "$rel_dir" > "$STATE_DIR/$mon"
        else
            apply_monitor "{ output = \"$mon\", mode = \"$mode\" }"
        fi
        ;;

    "Scale")
        scale=$(printf "1.0\n1.25\n1.5\n1.6667\n2.0\n" | rofi_menu "Scale (or type a custom value)")
        [ -z "$scale" ] && exit 0

        relation=$(get_relation "$mon" || true)
        if [ -n "$relation" ]; then
            rel_target=$(echo "$relation" | cut -f1)
            rel_dir=$(echo "$relation" | cut -f2)
            my_w=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name==$m) | .width')
            my_h=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name==$m) | .height')
            pos=$(compute_relative_position "$my_w" "$my_h" "$scale" "$rel_target" "$rel_dir")
            apply_monitor "{ output = \"$mon\", scale = $scale, position = \"$pos\" }"
            printf '%s\t%s\n' "$rel_target" "$rel_dir" > "$STATE_DIR/$mon"
        else
            apply_monitor "{ output = \"$mon\", scale = $scale }"
        fi
        ;;

    "Rotation")
        rot=$(printf "Normal\n90°\n180°\n270°\n" | rofi_menu "Rotation")
        [ -z "$rot" ] && exit 0
        case "$rot" in
            "Normal") t=0 ;; "90°") t=1 ;; "180°") t=2 ;; "270°") t=3 ;;
        esac
        apply_monitor "{ output = \"$mon\", transform = $t }"
        ;;

    "Enable")
        apply_monitor "{ output = \"$mon\", disabled = false }"
        ;;

    "Disable")
        apply_monitor "{ output = \"$mon\", disabled = true }"
        ;;

    "Mirror another display")
        others=$(echo "$json" | jq -r --arg m "$mon" '.[] | select(.name!=$m) | .name')
        [ -z "$others" ] && { echo "No other display to mirror." | rofi_menu "Mirror"; exit 0; }
        target=$(echo "$others" | rofi_menu "Mirror onto")
        [ -z "$target" ] && exit 0
        apply_monitor "{ output = \"$mon\", mirror = \"$target\" }"
        ;;

    "Reset to auto")
        apply_monitor "{ output = \"$mon\", mode = \"preferred\", position = \"auto\", scale = \"auto\" }"
        ;;
esac

sleep 0.3   # let hyprctl settle before re-reading state
save_all_monitors
# No `hyprctl reload` -- the eval call above already applied the change live.
