-- Auto-generated by display-menu.sh
-- Reflects live monitor state at last change. Don't hand-edit -- it will be overwritten.

hl.monitor({
    output    = "eDP-1",
    mode      = "1920x1080@60.00200",
    position  = "0x0",
    scale     = 1.25,
    transform = 0,
})

hl.monitor({
    output    = "HDMI-A-1",
    mode      = "1920x1080@60.00000",
    position  = "0x-1080",
    scale     = 1,
    transform = 0,
})

